version: '3'
services:

  video:
    image: bmehsnlab/aruco_detect_image_v2
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    networks:
      - host
    depends_on:
      - detect
    command: roslaunch root/catkin_ws/src/drone_flight_contorl/mantisvideo.launch

  detect:
    image: bmehsnlab/aruco_detect_image_v2
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    networks:
      - host
    depends_on:
      - control
    command: rosrun drone_flight_contorl drone_flight_contorl_node

  control:
    image: bmehsnlab/aruco_detect_image_v2
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    networks:
      - host
    depends_on:
      - master
    command: python /root/catkin_ws/src/drone_flight_contorl/scripts/aruco_felett_lebeg.py
  
  master:
    image: bmehsnlab/aruco_detect_image_v2
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    networks:
      - host
    command: roslaunch mavros px4.launch fcu_url:="udp://:14540@192.168.42.1:14557" &> log.txt &

networks:
  host: