version: '3'
services:
  video:
    image: "bmehsnlab/aruco_detect_image_v2"
    depends_on:
      - detector
    networks:
      - drone_host
      - drone_bridge
    command:
      - roslaunch root/catkin_ws/src/drone_flight_contorl/mantisvideo.launch
  detector:
    image: "bmehsnlab/aruco_detect_image_v2"
    depends_on:
      - control
    networks:
      - drone_bridge
    command:
      - rosrun drone_flight_contorl drone_flight_contorl_node
  control:
    image: "bmehsnlab/aruco_detect_image_v2"
    depends_on:
      - master
    networks:
      - drone_bridge
    command:
      - python /root/catkin_ws/src/drone_flight_contorl/scripts/aruco_felett_lebeg.py
  master:
    image: "bmehsnlab/aruco_detect_image_v2"
    networks:
      - drone_bridge
    command:
      - roslaunch mavros px4.launch fcu_url:="udp://:14540@192.168.42.1:14557" &> log.txt &

networks:
  drone_host:
    driver: host
  drone_bridge:
    driver: bridge