apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-1
  template:
    metadata:
      labels:
        app: drone-1
    spec:
      containers:
      - name: roscore
        image: nanasidnl/drone_control:roscore
        ports:
        - containerPort: 11311
      - name: aruco
        image: nanasidnl/drone_control:aruco
        env:
          - name: ROS_MASTER_URI
            value: "http://localhost:11311"
          - name: ARUCO_LAUNCH
            value: "sim"
      - name: commander
        image: nanasidnl/drone_control:commander
        ports: 
        - containerPort: 80
        env:
        - name: ROS_MASTER_URI
          value: "http://localhost:11311"
        - name: FCU_URL
          value: "udp://@:14580"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: drone-1-roscore
spec:
  ports:
  - port: 11311
    nodePort: 31311
    name: roscore
  selector:
    app: drone-1
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 10.253.192.163
---
apiVersion: v1
kind: Service
metadata:
  name: drone-1-commander
spec:
  ports:
  - port: 80
    nodePort: 30080
    name: dashboard
  selector:
    app: drone-1
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 10.253.192.163
