apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-hq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-hq
  template:
    metadata:
      labels:
        app: drone-hq
    spec:
      containers:
      - name: roscore
        image: nanasidnl/drone_control:roscore
        ports:
        - containerPort: 11311
      - name: aruco
        image: nanasidnl/drone_control:aruco
        env:
          - name: ROS_MASTER_URI
            value: "http://localhost:11311"
          - name: ARUCO_LAUNCH
            value: "sim"
      - name: commander
        image: nanasidnl/drone_control:commander
        ports: 
        - containerPort: 80
        env:
        - name: ROS_MASTER_URI
          value: "http://localhost:11311"
        - name: FCU_URL
          value: "udp://:14580@"
      - name: px4sim
        image: nanasidnl/drone_control:px4sim
        ports: 
        - containerPort: 10000
        - containerPort: 14580
        env:
        - name: ROS_MASTER_URI
          value: "http://localhost:11311"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: drone-hq
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
    name: dashboard
  - port: 10000
    nodePort: 30000
    name: gazebo
  - port: 11311
    nodePort: 31311
    name: roscore
  selector:
    app: drone-hq
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: ${MASTER_IP}
  