apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-hq
spec:
  selector:
    matchLabels:
      run: drone-hq
  replicas: 1
  template:
    metadata:
      labels:
        run: drone-hq
    spec:
      containers:
      - name: roscore
        image: nanasidnl/drone_control:roscore
      - name: aruco
        image: nanasidnl/drone_control:aruco
      - name: commander
        image: nanasidnl/drone_control:commander
        ports: 
        - name: dashboard
          containerPort: 11311
          protocol: TCP
      - name: px4sim
        image: nanasidnl/drone_control:px4sim
        ports: 
          - name: gazebo
            containerPort: 10001
            protocol: TCP
      imagePullSecrets:
      - name: regcred
