apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-hq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-hq
  template:
    metadata:
      labels:
        app: drone-hq
    spec:
      containers:
      - name: roscore
        image: nanasidnl/drone_control:roscore
      - name: aruco
        image: nanasidnl/drone_control:aruco
      - name: commander
        image: nanasidnl/drone_control:commander
        ports: 
        - containerPort: 11311
      - name: px4sim
        image: nanasidnl/drone_control:px4sim
        ports: 
        - containerPort: 10001
      imagePullSecrets:
        - name: regcred
---
apiVersion: apps/v1
kind: Service
metadata:
  name: drone-hq
spec:
  ports:
  - port: 80
    targetPort: 11311
    name: dashboard
  - port: 8080
    targetPort: 10001
    name: gazebo
