apiVersion: v1
kind: Service
metadata:
  name: drone-hq
  labels:
    app: drone-hq
spec:
  ports:
  - port: 80
    name: commander
  - port: 10000
    name: px4sim
  selector:
    app: drone-hq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-hq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-hq
  template:
    metadata:
      labels:
        app: drone-hq
    spec:
      containers:
      - name: roscore
        image: nanasidnl/drone_control:roscore
      - name: aruco
        image: nanasidnl/drone_control:aruco
        env:
        - name: ROS_MASTER_URI
          value: "http://roscore:11311"
        - name: ARUCO_LAUNCH
          value: "sim"
      - name: commander
        image: nanasidnl/drone_control:commander
        ports: 
        - containerPort: 80
        env:
        - name: ROS_MASTER_URI
          value: "http://roscore:11311"
        - name: FCU_URL
          value: "udp://@px4sim:14580"
      - name: px4sim
        image: nanasidnl/drone_control:px4sim
        ports: 
        - containerPort: 10000
        env:
        - name: ROS_MASTER_URI
          value: "http://roscore:11311"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Endpoints
metadata:
  name: drone-hq
subsets:
  - addresses:
      - ip: 10.56.88.198
    ports:
      - port: 80
        