apiVersion: apps/v1
kind: Deployment
metadata:
  name: roscore-$(DRONE_IDENTIFIER)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roscore-$(DRONE_IDENTIFIER)
  template:
    metadata:
      labels:
        app: roscore-$(DRONE_IDENTIFIER)
    spec:
      nodeSelector:
        dedicated: roscore-$(DRONE_IDENTIFIER)
      hostname: roscore-$(DRONE_IDENTIFIER)
      containers:
      - name: roscore-$(DRONE_IDENTIFIER)
        image: nanasidnl/drone_control:roscore
        env:
          - name: ROS_MASTER_URI
            value: http://$(ROSCORE_IP):$(MAVLINK_PORT)
          - name: ROS_IP
            value: $(ROSCORE_IP)
          - name: MAVLINK_PORT
            value: $(MAVLINK_PORT)
        args:
          - roscore
      nodeSelector: 
      hostNetwork: true