apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-$(DRONE_IDENTIFIER)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-$(DRONE_IDENTIFIER)
  template:
    metadata:
      labels:
        app: drone-$(DRONE_IDENTIFIER)
    spec:
      containers:
      - name: roscore
        image: nanasidnl/drone_control:roscore
        ports:
        - containerPort: 11311
      - name: aruco
        image: nanasidnl/drone_control:aruco
        env:
          - name: ROS_MASTER_URI
            value: "http://localhost:$(MAVLINK_PORT)"
          - name: ARUCO_LAUNCH
            value: "sim"
      - name: commander
        image: nanasidnl/drone_control:commander
        ports: 
        - containerPort: 80
        env:
        - name: ROS_MASTER_URI
          value: "http://localhost:$(MAVLINK_PORT)"
        - name: FCU_URL
          value: "udp://@$(DRONE_IP):$(FCU_PORT)"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: drone-$(DRONE_IDENTIFIER)
spec:
  ports:
  - port: 80
    name: dashboard
  - port: 11311
    name: roscore
  selector:
    app: drone-$(DRONE_IDENTIFIER)
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: $(MASTER_IP)
