apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-$(DRONE_IDENTIFIER)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-$(DRONE_IDENTIFIER)
  template:
    metadata:
      labels:
        app: drone-$(DRONE_IDENTIFIER)
    spec:
      containers:
      - name: aruco
        image: nanasidnl/drone_control:aruco
        env:
          - name: ROS_MASTER_URI
            value: "http://$(ROSCORE_IP):11311"
          - name: ARUCO_LAUNCH
            value: "sim"
      - name: commander
        image: nanasidnl/drone_control:commander
        ports: 
        - containerPort: $(COMMANDER_PORT)
        env:
        - name: ROS_MASTER_URI
          value: "http://$(ROSCORE_IP):11311"
        - name: FCU_URL
          value: "udp://@$(DRONE_IP):$(FCU_PORT)/"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: drone-$(DRONE_IDENTIFIER)-commander
spec:
  ports:
  - port: $(COMMANDER_PORT)
    nodePort: $(COMMANDER_NODE_PORT)
    name: dashboard
  selector:
    app: drone-$(DRONE_IDENTIFIER)
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: $(MASTER_IP)
