# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: drone-hq
  labels:
    run: drone-hq
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 11311
    protocol: TCP
    name: dashboard
  - port: 8080
    targetPort: 10001
    protocol: TCP
    name: gazebo
  selector:
    run: drone-hq

# DEPLOYMENT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-hq
spec:
  selector:
    matchLabels:
      run: drone-hq
  replicas: 1
  template:
    metadata:
      labels:
        run: drone-hq
    spec:
      containers:
      - name: aruco
        image: nanasidnl/drone_control:aruco
      - name: px4sim
        image: nanasidnl/drone_control:px4sim
      - name: commander
        image: nanasidnl/drone_control:commander
      - name: roscore
        image: nanasidnl/drone_control:roscore
      imagePullSecrets:
      - name: regcred
