apiVersion: apps/v1
kind: Deployment
metadata:
  name: roscore-$(DRONE_IDENTIFIER)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roscore-$(DRONE_IDENTIFIER)
  template:
    metadata:
      labels:
        app: roscore-$(DRONE_IDENTIFIER)
    spec:
      nodeSelector:
        dedicated: roscore-$(DRONE_IDENTIFIER)
      hostname: roscore-$(DRONE_IDENTIFIER)
      containers:
      - name: roscore-$(DRONE_IDENTIFIER)
        image: alpineros/alpine-ros:noetic-ros-core 
        env:
          - name: ROS_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ROS_MASTER_URI
            value: "http://$(ROS_IP):$(MAVLINK_PORT)"
        args: ["roscore", "-p", "$(MAVLINK_PORT)"]
      nodeSelector: 
      hostNetwork: true