apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: roscore-$(DRONE_IDENTIFIER)
spec:
  selector:
    matchLabels:
      app: roscore-$(DRONE_IDENTIFIER)
  template:
    metadata:
      labels:
        app: roscore-$(DRONE_IDENTIFIER)
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchFields:
              - key: metadata.name
                operator: NotIn
                values:
                - master
      hostname: roscore-$(DRONE_IDENTIFIER)
      containers:
      - name: roscore-$(DRONE_IDENTIFIER)
        image: alpineros/alpine-ros:noetic-ros-core 
        env:
          - name: ROS_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ROS_MASTER_URI
            value: "http://$(ROS_IP):$(MAVLINK_PORT)"
        args: ["roscore", "-p", "$(MAVLINK_PORT)"]
      hostNetwork: true
